#!/bin/bash

# Install udev rules and helper script to automount USB-C storage devices to
# /mnt/usb{n} where n reflects the physical port number.

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "configure-usb-automount.sh must be run as root" >&2
  exit 1
fi

TARGET_USER=${1:-}
if [[ -z "${TARGET_USER}" ]]; then
  echo "Usage: configure-usb-automount.sh <target-user>" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR=/usr/local/lib/arch-hyprland
BIN_PATH=${INSTALL_DIR}/usb-automount.sh
CONFIG_DIR=/etc/arch-hyprland
CONFIG_FILE=${CONFIG_DIR}/usb-automount.conf
RULES_FILE=/etc/udev/rules.d/99-arch-hyprland-usb-automount.rules

mkdir -p "${INSTALL_DIR}"
install -m 755 "${SCRIPT_DIR}/usb-automount-handler.sh" "${BIN_PATH}"

mkdir -p "${CONFIG_DIR}"
autogroup=$(id -gn "${TARGET_USER}")
cat >"${CONFIG_FILE}" <<EOF_CONF
# Generated by configure-usb-automount.sh
# Adjust mount root/prefix if you prefer a different target directory.
MOUNT_ROOT="/mnt"
MOUNT_PREFIX="usb"
# The login user that should own the mounted filesystem for access control.
AUTOMOUNT_USER="${TARGET_USER}"
AUTOMOUNT_GROUP="${autogroup}"
# Default mount options appended to filesystem-specific requirements.
MOUNT_OPTIONS="noatime"
# Runtime state directory used to track active mounts.
STATE_DIR="/run/arch-hyprland-usb"
EOF_CONF
chmod 640 "${CONFIG_FILE}"
chown root:root "${CONFIG_FILE}"

cat >"${RULES_FILE}" <<'EOF_RULES'
# Auto-mount USB mass storage partitions to predictable /mnt/usb{n} paths.
ACTION=="add", SUBSYSTEM=="block", ENV{DEVTYPE}=="partition", ENV{ID_BUS}=="usb", ENV{ID_FS_USAGE}=="filesystem", RUN+="/usr/local/lib/arch-hyprland/usb-automount.sh add %k"
ACTION=="remove", SUBSYSTEM=="block", ENV{DEVTYPE}=="partition", ENV{ID_BUS}=="usb", RUN+="/usr/local/lib/arch-hyprland/usb-automount.sh remove %k"
EOF_RULES
chmod 644 "${RULES_FILE}"

udevadm control --reload

cat <<EOF_MSG
Configured USB automount helper:
  - Script: ${BIN_PATH}
  - Config: ${CONFIG_FILE}
  - Udev rule: ${RULES_FILE}
Reloaded udev rules; newly attached USB storage will mount to /mnt/usb{n}.
EOF_MSG
