#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

echo "=== Corsair 4000D Fan Troubleshooting ==="
echo ""
echo "Checking fan detection..."

# Check current fan speeds
echo "Currently detected fans:"
sensors | grep -E "fan|rpm" || echo "No fans detected by sensors"

echo ""
echo "=== IMMEDIATE FIX OPTIONS ==="
echo ""
echo "1. CHECK PHYSICAL CONNECTIONS:"
echo "   - The 3 front fans should have TWO cables each:"
echo "     • RGB cable (connected to RGB hub) ✓ Working"
echo "     • PWM cable (4-pin) → Should connect to:"
echo "       - Motherboard headers labeled SYS_FAN or CHA_FAN"
echo "       - OR a PWM fan hub/splitter connected to motherboard"
echo ""
echo "2. IF FANS ARE CONNECTED TO MOTHERBOARD:"
echo "   Run these commands to force them on:"
echo ""
echo "   # Install fan control software"
echo "   sudo pacman -S lm_sensors fancontrol"
echo ""
echo "   # Detect sensors"
echo "   sudo sensors-detect --auto"
echo ""
echo "   # Configure fans"
echo "   sudo pwmconfig"
echo ""
echo "3. QUICK TEST - FORCE ALL FANS TO 100%:"
echo "   for pwm in /sys/class/hwmon/hwmon*/pwm*; do"
echo "     echo 255 | sudo tee \$pwm 2>/dev/null"
echo "   done"
echo ""
echo "4. BIOS SETTINGS TO CHECK:"
echo "   - Enter BIOS (Del or F2 on boot)"
echo "   - Go to Hardware Monitor or Fan Control"
echo "   - Set all CHA_FAN/SYS_FAN headers to:"
echo "     • PWM mode (not DC)"
echo "     • Standard or Performance curve"
echo "     • Minimum speed: 40-50%"
echo ""
echo "5. IF USING CORSAIR COMMANDER/LIGHTING NODE:"
echo "   The PWM cables might connect to a Corsair Commander unit"
echo "   Check for USB connection from Commander to motherboard"
echo ""
echo "=== DIAGNOSTIC INFO ==="
echo ""
echo "Motherboard fan headers found:"
ls /sys/class/hwmon/*/fan*_input 2>/dev/null | while read -r fan; do
    name="$(basename "$fan")"
    speed="$(cat "$fan" 2>/dev/null)"
    echo "  $name: $speed RPM"
done

echo ""
echo "PWM controls found:"
ls /sys/class/hwmon/*/pwm* 2>/dev/null | grep -v "_max\|_min" | head -5

echo ""
echo "USB devices (checking for Corsair Commander):"
lsusb | grep -i "corsair\|1b1c" || echo "No Corsair USB devices found"

echo ""
echo "=== MOST LIKELY ISSUE ==="
echo "The PWM cables from the 3 front fans are probably not connected"
echo "to the motherboard. RGB and PWM are separate systems."
echo ""
echo "Solution: Connect the 4-pin PWM cables from each fan to:"
echo "  - Motherboard headers: SYS_FAN1, SYS_FAN2, SYS_FAN3"
echo "  - OR use a PWM splitter to connect all 3 to one header"
